spring:
  application:
    name: gateway
server:
  port: 8080
eureka:
  client:
    enabled: false
  instance:
    prefer-ip-address: true
resource:
  server: ${RESOURCE_SERVICE:lb://RESOURCE-SERVICE}