spring:
  security:
    oauth2:
      resourceserver:
        jwt:
          jwk-set-uri: ${KEYCLOAK_SERVER_URL:http://localhost:8080}/realms/inspire/protocol/openid-connect/certs
eureka:
  instance:
    prefer-ip-address: true
  client:
    enabled: ${EUREKA_CLIENT_ENABLED:true}
    serviceUrl:
      defaultZone: ${EUREKA_SERVICE_URL:http://localhost:8761/eureka}
server:
  port: 8082
keycloak:
  policy-enforcer:
    realm: ${KEYCLOAK_REALM_NAME:inspire}
    auth-server-url: ${KEYCLOAK_SERVER_URL:http://localhost:8080}
    resource: ${KEYCLOAK_CLIENT_ID:inspire-client}
    credentials:
      secret: ${KEYCLOAK_CLIENT_SECRET:vYNJUuz0o2Oux2iCI78MU926BsZYkMky}