server.port: 8082
spring:
  output:
    ansi:
      enabled: always
  security:
    oauth2:
      resourceserver:
        jwt:
          jwk-set-uri: http://localhost:8080/realms/inspire/protocol/openid-connect/certs
logging:
  level:
    root: INFO
    org:
      keycloak: DEBUG
      keycloak.adapters: DEBUG