spring:
  application:
    name: resource-service
  output:
    ansi:
      enabled: always
  profiles:
    active: @active@
logging:
  level:
    root: INFO
    org:
      keycloak: DEBUG
      keycloak.adapters: DEBUG