spring:
  security:
    oauth2:
      resourceserver:
        jwt:
          jwk-set-uri: http://keycloak:8080/realms/inspire/protocol/openid-connect/certs
eureka:
  instance:
    prefer-ip-address: true
  client:
    enabled: ${EUREKA_CLIENT_ENABLED:true}
    serviceUrl:
      defaultZone: ${EUREKA_SERVICE_URL:http://eureka-server:8761/eureka}
server:
  port: 8080

keycloak:
  policy-enforcer:
    realm: inspire
    auth-server-url: http://keycloak:8080
    resource: inspire-client
    credentials:
      secret: vYNJUuz0o2Oux2iCI78MU926BsZYkMky